### ISSUE TITLE
comics appears empty no matter what

### ISSUE THREAD

**Issue by krodelabestiole** [linuxserver/docker-ubooquity#22]
nothing much to say : I tripled checked the path related to comics was ok, but it never worked :
opening a shell inside the container always shows /comics is empty.

no problem with /books

I ended up linking my host comics path to a new directory name, and adding this directory as a comics shared folder in ubooquity admin.

This way it works, but still...

**Comment by homerr** [comment]
Can you provide your docker run command or docker-compose snippet please as a starting point so we can figure this out.

**Comment by krodelabestiole** [comment]
docker-compose.yml :

```
version: '3'
  ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    ports:
    - '2202:2202'
    - '2203:2203'
    volumes:
    - '/home/krodelabestiole/ubooquity:/config'
    - '/mnt/usb/fatcap/books/comics:/comics'
    - '/mnt/usb/fatcap/books/books:/books'
    environment:
    - PGID=1000
    - PUID=1000
    restart: always
```

I replaced the second volume with /mnt/usb/fatcap/books/comics:/bds
(bds = comics in french) and it worked
I have no idea why /comics appears empty in the container while /mnt/usb/fatcap/books/comics is definitely not.
