### ISSUE TITLE
Database persistency issues

### ISSUE THREAD

**Issue by francispeixoto** [linuxserver/docker-ubooquity#28]
Full disclosure, I might not be technical enough to properly describe what's going on. This is my perception of the effects of what I believe to be a bug.

It seems that the database isn't properly persisted when the container image is updated. I have Watchtower maintaining my image versions, and as long as it doesn't update Ubooquity, the database is properly maintained, with recent additions being tracked incrementally as expected. But as soon as the image gets updated, the scan scan starts other from scratch, as if the database hadn't existed before.

**Comment by tobbenb** [comment]
Post the compose file or the run command you used to deploy the container.

**Comment by francispeixoto** [comment]
this is what I have in my composer file: 

```
 ubooquity:
    image: linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MAXMEM=
    volumes:
      - ${USERDIR}/docker/ubooquity:/config
      - /media/data/books:/books
      - /media/data/comics:/comics
      - /media/data:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped
```

this is the latest image that watchtower grabbed:

`time="2019-05-06T04:00:33Z" level=info msg="Found new linuxserver/ubooquity:latest image (sha256:b920a33730212dc4f23dc32154e6a8bb4273982d47a6dc33ca83d7d64ab689bb)"`
